### ISSUE TITLE
Alternative API?

### ISSUE THREAD

**Issue by clarkewd** [pxgamer/dirtyapi#2]
Since the API at DirtyMarkup seems to be down, do you have any suggestions for another service or code library that could work with this library? Thank you!

**Comment by owenvoke** [comment]
I'd completely forgotten about this package, as I haven't used it since I released it.

Looks like DirtyMarkup shut down, so I will archive this package.

As an alternative, you may be able to use an API such as [this one by Beautify Code](https://beautifycode.net/api-information) or something similar. Bear in mind, I don't use this myself so I can't really recommend any specific API.
